project:
  type: website
  output-dir: docs

website:
  title: "Xuan-Ai Pham, PhD Researcher"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: resume.qmd
        text: Resume
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo dark
    css: styles.css
    toc: true

editor: visual

